---
permalink: intro-family.html 
keywords: introduction, how astra works, how Astra works, what Astra is, astra control, kubernetes, astra control service, astra control center 
summary: Astra は、 Kubernetes アプリケーションデータライフサイクル管理サービスで、ステートフルアプリケーションの運用を簡易化します。Kubernetes ワークロードの保護、バックアップ、移行を簡易化し、作業用アプリケーションのクローンを瞬時に作成できます。 
---
= Astra Controlの詳細をご確認ください
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Astra Control は、ステートフル アプリケーションの操作を簡素化し、ハイブリッド環境全体で Kubernetes ワークロードを保存、保護、移動できるようにする Kubernetes アプリケーション データ ライフサイクル管理ソリューションです。



== 機能

Astra Control は、 Kubernetes アプリケーションデータのライフサイクル管理に不可欠な機能を提供

*ストア*：

* コンテナ化されたワークロード向けの動的なストレージプロビジョニング
* コンテナから永続的ボリュームへの転送中データの暗号化
* リージョン間、ゾーン間レプリケーション


*保護*：

* アプリケーション全体とそのデータを自動検出し、アプリケーション対応の保護を実現
* 組織のニーズに基づいて'任意のスナップショット・バージョンからアプリケーションを即座にリカバリ
* ゾーン、リージョン、クラウドプロバイダ間で高速フェイルオーバー


*移動*：

* Kubernetesクラスタとクラウド間でアプリケーションとデータを完全に移動
* アプリケーションとデータ全体を瞬時にクローニング
* 一貫したWeb UIとAPIでワンクリックでアプリケーションを移行




== アーキテクチャ

IT部門はAstra Controlのアーキテクチャにより、高度なデータ管理機能を提供できるようになり、Kubernetesアプリケーションの機能と可用性の両方を強化し、パブリッククラウドとオンプレミス環境にわたるコンテナ化されたワークロードの管理、保護、移動を簡易化できます。 また、REST APIとSDKを使用した自動化機能を提供し、プログラム経由でアクセスして既存のワークフローとシームレスに統合できます。

Astra ControlはKubernetesネイティブであるため、既存のAPIやSDKとの後方互換性を維持しながら、カスタムリソースを活用するデータ保護ワークフローを実現できます。Kubernetesネイティブのデータ保護には大きなメリットがあります。KubernetesのAPIやリソースとシームレスに統合することで、組織の既存のCI / CDツールやGitOpsツールを通じて、データ保護がアプリケーションのライフサイクルに本質的に組み込まれるようになります。

Astra Controlは、次の4つのコンポーネントを基盤として構築されています。

* *Astra Control*: Astra Control は、すべての管理対象クラスターの集中管理サービスであり、オンプレミスのアプリケーション保護とモビリティのためのオーケストレーションされたワークロードと次の機能を提供します。
+
** 複数のクラスターを組み合わせたビュー
** オーケストレーションされたワークフローの保護
** きめ細かなリソースの視覚化と選択


* * Astra Connector *：Astra Connectorは、Astra Controlと連携して各管理対象クラスタへのセキュアな接続を提供し、接続ステータスに関係なくスケジュールされた処理をローカルで実行できるようにします。また、次の機能も提供します。
+
** 接続ステータスに関係なく、スケジュールされた操作をローカルで実行
** Astraのシステムリソース使用量をクラスタ間で分散、最適化するローカル運用
** セキュリティを向上させるために、クラスタへの最小限の権限でのアクセスを可能にするローカルインストール


* * Astra Control Provisioner *：Astra Control Provisionerは、CSIのコアプロビジョニング機能と高度なストレージ管理機能を提供し、セキュリティとディザスタリカバリの設定を強化します。さらに、以下の機能も提供します。
+
** コンテナ化されたワークロード向けの動的なストレージプロビジョニング
** 高度なストレージ管理：
+
*** コンテナからPVへのデータの転送中暗号化
*** リージョン間、ゾーン間レプリケーションを使用したSnapMirror Cloud機能




* * Astraカスタムリソース*：各クラスタで使用されるカスタムリソースにより、Kubernetesネイティブのアプローチでローカルで運用を実行できるため、Kubernetesに対応した他のツールや自動化との統合が簡易化され、次の機能が提供されます。
+
** エコシステムツールの直接統合と自動化のワークフロー
** カスタムワークフローを可能にする下位レベルのプリミティブ






== 導入モデル

Astra Control は単一の展開モデルで利用できます。

* Astra Control Center * ：オンプレミス環境で実行される Kubernetes クラスタのアプリケーション対応データ管理を提供する、自己管理ソフトウェアです。NetApp Cloud Volumes ONTAP ストレージバックエンドを使用して、複数のクラウドプロバイダ環境にAstra Control Centerをインストールすることもできます。

https://docs.netapp.com/us-en/astra-control-center/["Astra Control Center のドキュメント"^]

[cols="1h,2d"]
|===
|  | Astra Control Center の略 


| どのような方法で提供されますか？ | ソフトウェアとしてダウンロード、インストール、および管理できます 


| ホストされているのはどこですか？ | 自社所有のKubernetesクラスタ 


| 更新方法 | 更新を管理します 


| サポートされているKubernetesディストリビューションを教えてください。  a| 
* Azure Stack HCIで実行されるAzure Kubernetes Service
* Google Anthos
* Kubernetes（アップストリーム）
* Rancher Kubernetes Engine （ RKE ）
* Red Hat OpenShift Container Platform




| サポートされているストレージバックエンドは何ですか。  a| 
* NetApp ONTAP AFF および FAS システム
* NetApp ONTAP Select の略
* https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/["Cloud Volumes ONTAP"^]
* https://longhorn.io/["ロングホーン""^]


|===


== を参照してください。

* https://docs.netapp.com/us-en/astra-control-center/["Astra Control Center のドキュメント"^]
* https://docs.netapp.com/us-en/trident/index.html["Astra Trident のドキュメント"^]
* https://docs.netapp.com/us-en/astra-automation/index.html["Astra Control API の略"^]
* https://docs.netapp.com/us-en/cloudinsights/["Cloud Insights のドキュメント"^]
* https://docs.netapp.com/us-en/ontap/index.html["ONTAP のドキュメント"^]

