---
permalink: intro-family.html 
keywords: introduction, how astra works, how Astra works, what Astra is, astra control, kubernetes, astra control service, astra control center 
summary: Astra は、 Kubernetes アプリケーションデータライフサイクル管理サービスで、ステートフルアプリケーションの運用を簡易化します。Kubernetes ワークロードの保護、バックアップ、移行を簡易化し、作業用アプリケーションのクローンを瞬時に作成できます。 
---
= Astra製品ファミリーの詳細をご確認ください
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
ネットアップのAstra製品ファミリーは、クラウドネイティブアプリケーション向けのアプリケーションデータ管理とストレージを提供します。

Astra には次のサービスがあります。

* * Astra Control * ：パブリッククラウドとオンプレミスの両方で Kubernetes ワークロードを管理、保護、移動する、アプリケーション対応のデータ管理ツールを使用。 3 つの制約が発生
+
** * Astra Control Service * ：ネットアップが管理するサービスを使用して、パブリッククラウドの Kubernetes ワークロードをデータ管理
** * Astra Control Center * ：オンプレミスの Kubernetes ワークロードのデータ管理に、自己管理ソフトウェアを使用


* * Astra Trident * ： Container Storage Interface （ CSI ）に準拠したストレージプロビジョニングと管理を、ネットアップのストレージプロバイダとともに使用します。




== Astra Control の略

Astra Control は、 Kubernetes アプリケーションデータライフサイクル管理解決策で、ステートフルアプリケーションの運用を簡易化します。Kubernetes ワークロードの保護、バックアップ、移行を簡易化し、作業用アプリケーションのクローンを瞬時に作成できます。



=== の機能

Astra Control は、 Kubernetes アプリケーションデータのライフサイクル管理に不可欠な機能を提供

* 永続的ストレージを自動的に管理
* アプリケーション対応のオンデマンドの Snapshot とバックアップを作成
* ポリシーベースのスナップショットおよびバックアップ操作を自動化します
* Kubernetes クラスタ間でアプリケーションとデータを移行
* NetApp SnapMirrorテクノロジを使用してアプリケーションをリモートシステムにレプリケート（Astra Control Center）
* ステージング環境から本番環境へのアプリケーションのクローニング
* アプリケーションの稼働状態と保護状態を視覚化します
* Web UIまたはAPIを使用して、バックアップと移行のワークフローを実装します




=== 導入モデル

Astra Control には、次の 2 つの導入モデルがあります。

* * Astra Control Service *：複数のクラウドプロバイダ環境および自己管理型KubernetesクラスタのKubernetesクラスタに対して、アプリケーション対応のデータ管理を提供する、ネットアップのマネージドサービスです。
+
https://docs.netapp.com/us-en/astra/index.html["Astra Control Service のマニュアル"^]

* * Astra Control Center * ：オンプレミス環境で実行される Kubernetes クラスタのアプリケーション対応データ管理を提供する、自己管理ソフトウェアです。NetApp Cloud Volumes ONTAP ストレージバックエンドを使用して、複数のクラウドプロバイダ環境にAstra Control Centerをインストールすることもできます。
+
https://docs.netapp.com/us-en/astra-control-center/["Astra Control Center のドキュメント"^]



[cols="1h,2a,2a"]
|===
|  | Astra 制御サービス | Astra Control Center の略 


| どのような方法で提供されますか？  a| 
ネットアップのフルマネージドクラウドサービス
 a| 
ソフトウェアとしてダウンロード、インストール、および管理します



| ホストされているのはどこですか？  a| 
ネットアップが選択したパブリッククラウドで実現
 a| 
自社所有のKubernetesクラスタ



| 更新方法  a| 
管理はネットアップが行います
 a| 
更新を管理します



| ストレージバックエンドでサポートされるもの  a| 
* Amazon Web Servicesの特長
+
** Amazon EBSのことです
** NetApp ONTAP 対応の Amazon FSX
** link:https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-getting-started-aws.html["Cloud Volumes ONTAP"^]


* Google Cloud
+
** Google Persistent Disk のことです
** NetApp Cloud Volumes Service の略
** link:https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-getting-started-gcp.html["Cloud Volumes ONTAP"^]


* Microsoft Azure
+
** Azure Managed Disksの略
** Azure NetApp Files の特長
** link:https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-getting-started-azure.html["Cloud Volumes ONTAP"^]


* 自己管理クラスタ：
+
** Amazon EBSのことです
** Google Persistent Disk のことです
** Azure Managed Disksの略
** link:https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/concept-overview-cvo.html["Cloud Volumes ONTAP"^]



 a| 
* NetApp ONTAP AFF および FAS システム
* link:https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/concept-overview-cvo.html["Cloud Volumes ONTAP"^]


|===


== Astra Trident

Astra Trident は、 Kubernetes Container Storage Interface （ CSI ）ドライブユーザーの間で行われるネットアップのオープンソース実装です。Astra Trident が Kubernetes アプリケーションのオーケストレーションとデータ接続を実現

https://docs.netapp.com/us-en/trident/index.html["Astra Trident のドキュメント"^]



== を参照してください。

* https://docs.netapp.com/us-en/astra/index.html["Astra Control Service のマニュアル"^]
* https://docs.netapp.com/us-en/astra-control-center/["Astra Control Center のドキュメント"^]
* https://docs.netapp.com/us-en/trident/index.html["Astra Trident のドキュメント"^]
* https://docs.netapp.com/us-en/astra-automation/index.html["Astra Control API の略"^]
* https://docs.netapp.com/us-en/cloudinsights/["Cloud Insights のドキュメント"^]
* https://docs.netapp.com/us-en/ontap/index.html["ONTAP のドキュメント"^]

